version: '3.9'
services:
  easops_web:
    build: .
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_SITE_URL: http://localhost:3000
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
